### PR TITLE
pass hostnamePlusPath if no name is passed to page call.

### PR DESCRIPTION
**Pull request by bbeaird**
https://segment.zendesk.com/agent/tickets/33203

### CODE REVIEW

**Comment by sperand-io** [comment]
@bbeaird like you, i have doubts regarding this implementation due to the `.` delimiting :disappointed:. perhaps the page `title` is a more apt fallback for `name` — have we reached out to the folks at quantcast directly? they've been super helpful in the past.

**Comment by sperand-io** [comment]
barring confirmation this is a WIP — **don't merge** just yet.

**Comment by sperand-io** [comment]
@bbeaird any word?

**Comment by f2prateek** [comment]
@bbeaird any updates from Quantcast?

**Comment by f2prateek** [comment]
Closing this for now.

**Comment by f2prateek** [comment]
Feel free to reopen if there are updates form Quantcast.

**Pull request closed without merging**
